### PR TITLE
Replace `Indexer` with `itertools.count`

### PR DESCRIPTION
**Pull request by mathiasose**
This PR is fairly insignificant by itself. It should change no functionality, just reduce the size of the codebase a tiny bit. I have tested locally with Py2 and Py3 and all the nosetests passed.

I was messing around with the indexer object to create a new type of indexer that assigns random UUIDs instead of sequential integers. While doing that I realized that the functionality of the indexer was just a re-implementation of `itertools.count`. So I though that I might as well just replace it with the built-in.

An added advantage is that instead of using the `indexer.get_next()` method, we change to use the iterator interface with `next(indexer)`. This makes it easier to drop in *any* iterator as a replacement indexer, such as my UUID-indexer. I might make another PR later with configuration for changing indexers.

### CODE REVIEW

**Comment by drallensmith** [comment]
Makes sense. A question and a comment:
- How are you preventing duplicates with the randomization (and what's the advantage)?
- At least one other version of NEAT actually uses the same ID for identical mutations occurring in the same generation (for NEAT-Python, this would be if the same connection was replaced with a node more than once in a given generation - quite probable in the first few generations, actually). I've noted this as a possible TODO (to allow this as an option).

**Comment by drallensmith** [comment]
Makes sense. A question and a comment:
- How are you preventing duplicates with the randomization (and what's the advantage)?
- At least one other version of NEAT actually uses the same ID for identical mutations occurring in the same generation (for NEAT-Python, this would be if the same connection was replaced with a node more than once in a given generation - quite probable in the first few generations, actually). I've noted this as a possible TODO (to allow this as an option).

**Comment by mathiasose** [comment]
> How are you preventing duplicates with the randomization?

The philosophy of the UUID type is that you're using so many bits (128) that the probability of a collision is astronomically low. See https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions for the math.

> what's the advantage?

The advantage is that you can discard your indexer at any time and make a new one when you need it. I needed this behavior in https://github.com/mathiasose/CA-NEAT to parallelize the algorithm using `celery`. In my custom `celery` EA loop there was no process that lived for the entire lifetime of the experiment, so nowhere to keep the counter. I thought about passing the counter value as a message from one process to another, but went with the random indices since I thought it was simpler.

About the CA-NEAT repo: the code is a bit messy (I didn't have a set plan, just implemented things as I needed them) and not suitable for merging into neat-python directly, so I'm re-implementing some of my changes that I think might be useful to others.

**Comment by CodeReclaimers** [comment]
Thanks for the patch!  I've been annoyed by Indexer for a while, but it never occurred to me that same functionality was already present in itertools. :)

**Pull request merged**
